# Indices of instance data
X_COORDINATE_IDX = 0
Y_COORDINATE_IDX = 1
VIS_DURATION_TIME_IDX = 2
OPENING_TIME_WINDOW_IDX = 3
CLOSING_TIME_WINDOW_IDX = 4
REWARD_IDX = 5
ARRIVAL_TIME_IDX = 6

# For generating instances
SAMP_DAY_FRAC_INF = 4/24.
UB_T_INIT_FRAC = 15/24.
LB_T_MAX_FRAC = 12/24.
CORR_SCORE_STD = 10

MULTIPLE_SCORE = 1.1

X_MAX = 100. # max square length (X_MAX)
